package com.wozimer.cataloger.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrame {
    private JPanel contentPanel;
    private JButton exitButton;
    private JPanel leftPanel;
    private JButton startPointsButton;
    private JTextArea logArea;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public MainFrame() {
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Component source = (Component) e.getSource();
                Window window = findWindow(source);
                if (window != null)
                    window.dispose();
            }

            private Window findWindow(Component source) {
                while (source != null) {
                    if ((source instanceof Window))
                        return (Window) source;
                    source = source.getParent();
                }
                return null;
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridBagLayout());
        contentPanel.add(leftPanel, BorderLayout.WEST);
        startPointsButton = new JButton();
        startPointsButton.setActionCommand("startPointsWindow");
        startPointsButton.setText("Начала");
        startPointsButton.setToolTipText("Начальные точки");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        leftPanel.add(startPointsButton, gbc);
        exitButton = new JButton();
        exitButton.setActionCommand("exit");
        exitButton.setText("Выход");
        exitButton.setToolTipText("Выход из приложения");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        leftPanel.add(exitButton, gbc);
        logArea = new JTextArea();
        logArea.setColumns(80);
        logArea.setEditable(false);
        logArea.setRows(20);
        contentPanel.add(logArea, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
